
MERGE INTO users AS target
USING #users_temp AS source
ON target.id = source.id
WHEN MATCHED THEN
	UPDATE SET
		target.type = source.type,
		target.origin = source.origin,
		target.name = source.name,
		target.legalName = source.legalName,
		target.preferredName = source.preferredName,
		target.lastname = source.lastname,
		target.avatar = source.avatar,
		target.email = source.email,
		target.timezone = source.timezone,
		target.hoursCap = source.hoursCap,
		target.active = source.active,
		target.deactivatedAt = source.deactivatedAt,
		target.timeclockEnabled = source.timeclockEnabled,
		target.phone = source.phone,
		target.hireDate = source.hireDate,
		target.birthdayDate = source.birthdayDate,
		target.countryCode = source.countryCode,
		target.countryISOCode = source.countryISOCode,
		target.role = source.role,
		target.employeeId = source.employeeId,
		target.address = source.address,
		target.additionalEmail = source.additionalEmail,
		target.emergencyContact = source.emergencyContact,
		target.emergencyContactRelationship = source.emergencyContactRelationship,
		target.emergencyContactPhone = source.emergencyContactPhone,
		target.emergencyContactCountryCode = source.emergencyContactCountryCode,
		target.emergencyContactCountryISOCode = source.emergencyContactCountryISOCode,
		target.status = source.status,
		target.pending = source.pending,
		target.defaultAvatar = source.defaultAvatar,
		target.deleted = source.deleted,
		target.createdAt = source.createdAt,
		target.joinedAt = source.joinedAt,
		target.hidden = source.hidden,
		target.ETLUpdatedAt = GETDATE()
WHEN NOT MATCHED THEN
	INSERT (
		id,
		type,
		origin,
		name,
		legalName,
		preferredName,
		lastname,
		avatar,
		email,
		timezone,
		hoursCap,
		active,
		deactivatedAt,
		timeclockEnabled,
		phone,
		hireDate,
		birthdayDate,
		countryCode,
		countryISOCode,
		role,
		employeeId,
		address,
		additionalEmail,
		emergencyContact,
		emergencyContactRelationship,
		emergencyContactPhone,
		emergencyContactCountryCode,
		emergencyContactCountryISOCode,
		status,
		pending,
		defaultAvatar,
		deleted,
		createdAt,
		joinedAt,
		hidden,
		ETLCreatedAt
	)
	VALUES (
		source.id,
		source.type,
		source.origin,
		source.name,
		source.legalName,
		source.preferredName,
		source.lastname,
		source.avatar,
		source.email,
		source.timezone,
		source.hoursCap,
		source.active,
		source.deactivatedAt,
		source.timeclockEnabled,
		source.phone,
		source.hireDate,
		source.birthdayDate,
		source.countryCode,
		source.countryISOCode,
		source.role,
		source.employeeId,
		source.address,
		source.additionalEmail,
		source.emergencyContact,
		source.emergencyContactRelationship,
		source.emergencyContactPhone,
		source.emergencyContactCountryCode,
		source.emergencyContactCountryISOCode,
		source.status,
		source.pending,
		source.defaultAvatar,
		source.deleted,
		source.createdAt,
		source.joinedAt,
		source.hidden,
		GETDATE()
	);

