
		MERGE INTO labor_report AS target
		USING #labor_report_temp AS source
		ON target.userId = source.userId and target.date = source.date and target.locationId = source.locationId and target.positionId = source.positionId
		WHEN MATCHED THEN
			UPDATE SET
				target.userId = source.userId,
				target.date = source.date,
				target.locationId = source.locationId,
				target.positionId = source.positionId,
				target.isSalary = source.isSalary,
				target.estimatedWages = source.estimatedWages,
				target.hours = source.hours,
				target.overtimeHours = source.overtimeHours,
				target.overtimeCost = source.overtimeCost,
				target.overtimeDayHours = source.overtimeDayHours,
				target.overtimeDayCost = source.overtimeDayCost,
				target.overtimeDoubleDailyHours = source.overtimeDoubleDailyHours,
				target.overtimeDoubleDailyCost = source.overtimeDoubleDailyCost,
				target.shiftsCount = source.shiftsCount,
				target.scheduledHolidayHours = source.scheduledHolidayHours,
				target.scheduledHolidayOvertimeHours = source.scheduledHolidayOvertimeHours,
				target.scheduledHolidayRegularCost = source.scheduledHolidayRegularCost,
				target.scheduledHolidayOvertimeCost = source.scheduledHolidayOvertimeCost,
				target.scheduledSpreadOfHoursCost = source.scheduledSpreadOfHoursCost,
				target.ptoHours = source.ptoHours,
				target.ptoCost = source.ptoCost,
				target.actualWages = source.actualWages,
				target.actualHours = source.actualHours,
				target.actualShiftsCount = source.actualShiftsCount,
				target.actualOvertimeHours = source.actualOvertimeHours,
				target.actualOvertimeCost = source.actualOvertimeCost,
				target.actualOvertimeDayHours = source.actualOvertimeDayHours,
				target.actualOvertimeDayCost = source.actualOvertimeDayCost,
				target.actualOvertimeDoubleDailyHours = source.actualOvertimeDoubleDailyHours,
				target.actualOvertimeDoubleDailyCost = source.actualOvertimeDoubleDailyCost,
				target.actualHolidayHours = source.actualHolidayHours,
				target.actualHolidayOvertimeHours = source.actualHolidayOvertimeHours,
				target.actualHolidayRegularCost = source.actualHolidayRegularCost,
				target.actualHolidayOvertimeCost = source.actualHolidayOvertimeCost,
				target.actualSpreadOfHoursCost = source.actualSpreadOfHoursCost,
				target.estimatedWagesStr = source.estimatedWagesStr,
				target.hoursStr = source.hoursStr,
				target.overtimeHoursStr = source.overtimeHoursStr,
				target.overtimeCostStr = source.overtimeCostStr,
				target.overtimeDayHoursStr = source.overtimeDayHoursStr,
				target.overtimeDayCostStr = source.overtimeDayCostStr,
				target.overtimeDoubleDailyHoursStr = source.overtimeDoubleDailyHoursStr,
				target.overtimeDoubleDailyCostStr = source.overtimeDoubleDailyCostStr,
				target.scheduledHolidayHoursStr = source.scheduledHolidayHoursStr,
				target.scheduledHolidayOvertimeHoursStr = source.scheduledHolidayOvertimeHoursStr,
				target.scheduledHolidayRegularCostStr = source.scheduledHolidayRegularCostStr,
				target.scheduledHolidayOvertimeCostStr = source.scheduledHolidayOvertimeCostStr,
				target.scheduledSpreadOfHoursCostStr = source.scheduledSpreadOfHoursCostStr,
				target.ptoHoursStr = source.ptoHoursStr,
				target.ptoCostStr = source.ptoCostStr,
				target.actualWagesStr = source.actualWagesStr,
				target.actualHoursStr = source.actualHoursStr,
				target.actualOvertimeHoursStr = source.actualOvertimeHoursStr,
				target.actualOvertimeCostStr = source.actualOvertimeCostStr,
				target.actualOvertimeDayHoursStr = source.actualOvertimeDayHoursStr,
				target.actualOvertimeDayCostStr = source.actualOvertimeDayCostStr,
				target.actualOvertimeDoubleDailyHoursStr = source.actualOvertimeDoubleDailyHoursStr,
				target.actualOvertimeDoubleDailyCostStr = source.actualOvertimeDoubleDailyCostStr,
				target.actualHolidayHoursStr = source.actualHolidayHoursStr,
				target.actualHolidayOvertimeHoursStr = source.actualHolidayOvertimeHoursStr,
				target.actualHolidayRegularCostStr = source.actualHolidayRegularCostStr,
				target.actualHolidayOvertimeCostStr = source.actualHolidayOvertimeCostStr,
				target.actualSpreadOfHoursCostStr = source.actualSpreadOfHoursCostStr,
				target.ETLUpdatedAt = GETDATE()
		WHEN NOT MATCHED THEN
			INSERT (
				userId,
				date,
				locationId,
				positionId,
				isSalary,
				estimatedWages,
				hours,
				overtimeHours,
				overtimeCost,
				overtimeDayHours,
				overtimeDayCost,
				overtimeDoubleDailyHours,
				overtimeDoubleDailyCost,
				shiftsCount,
				scheduledHolidayHours,
				scheduledHolidayOvertimeHours,
				scheduledHolidayRegularCost,
				scheduledHolidayOvertimeCost,
				scheduledSpreadOfHoursCost,
				ptoHours,
				ptoCost,
				actualWages,
				actualHours,
				actualShiftsCount,
				actualOvertimeHours,
				actualOvertimeCost,
				actualOvertimeDayHours,
				actualOvertimeDayCost,
				actualOvertimeDoubleDailyHours,
				actualOvertimeDoubleDailyCost,
				actualHolidayHours,
				actualHolidayOvertimeHours,
				actualHolidayRegularCost,
				actualHolidayOvertimeCost,
				actualSpreadOfHoursCost,
				estimatedWagesStr,
				hoursStr,
				overtimeHoursStr,
				overtimeCostStr,
				overtimeDayHoursStr,
				overtimeDayCostStr,
				overtimeDoubleDailyHoursStr,
				overtimeDoubleDailyCostStr,
				scheduledHolidayHoursStr,
				scheduledHolidayOvertimeHoursStr,
				scheduledHolidayRegularCostStr,
				scheduledHolidayOvertimeCostStr,
				scheduledSpreadOfHoursCostStr,
				ptoHoursStr,
				ptoCostStr,
				actualWagesStr,
				actualHoursStr,
				actualOvertimeHoursStr,
				actualOvertimeCostStr,
				actualOvertimeDayHoursStr,
				actualOvertimeDayCostStr,
				actualOvertimeDoubleDailyHoursStr,
				actualOvertimeDoubleDailyCostStr,
				actualHolidayHoursStr,
				actualHolidayOvertimeHoursStr,
				actualHolidayRegularCostStr,
				actualHolidayOvertimeCostStr,
				actualSpreadOfHoursCostStr,
				ETLCreatedAt
			)
			VALUES (
				source.userId,
				source.date,
				source.locationId,
				source.positionId,
				source.isSalary,
				source.estimatedWages,
				source.hours,
				source.overtimeHours,
				source.overtimeCost,
				source.overtimeDayHours,
				source.overtimeDayCost,
				source.overtimeDoubleDailyHours,
				source.overtimeDoubleDailyCost,
				source.shiftsCount,
				source.scheduledHolidayHours,
				source.scheduledHolidayOvertimeHours,
				source.scheduledHolidayRegularCost,
				source.scheduledHolidayOvertimeCost,
				source.scheduledSpreadOfHoursCost,
				source.ptoHours,
				source.ptoCost,
				source.actualWages,
				source.actualHours,
				source.actualShiftsCount,
				source.actualOvertimeHours,
				source.actualOvertimeCost,
				source.actualOvertimeDayHours,
				source.actualOvertimeDayCost,
				source.actualOvertimeDoubleDailyHours,
				source.actualOvertimeDoubleDailyCost,
				source.actualHolidayHours,
				source.actualHolidayOvertimeHours,
				source.actualHolidayRegularCost,
				source.actualHolidayOvertimeCost,
				source.actualSpreadOfHoursCost,
				source.estimatedWagesStr,
				source.hoursStr,
				source.overtimeHoursStr,
				source.overtimeCostStr,
				source.overtimeDayHoursStr,
				source.overtimeDayCostStr,
				source.overtimeDoubleDailyHoursStr,
				source.overtimeDoubleDailyCostStr,
				source.scheduledHolidayHoursStr,
				source.scheduledHolidayOvertimeHoursStr,
				source.scheduledHolidayRegularCostStr,
				source.scheduledHolidayOvertimeCostStr,
				source.scheduledSpreadOfHoursCostStr,
				source.ptoHoursStr,
				source.ptoCostStr,
				source.actualWagesStr,
				source.actualHoursStr,
				source.actualOvertimeHoursStr,
				source.actualOvertimeCostStr,
				source.actualOvertimeDayHoursStr,
				source.actualOvertimeDayCostStr,
				source.actualOvertimeDoubleDailyHoursStr,
				source.actualOvertimeDoubleDailyCostStr,
				source.actualHolidayHoursStr,
				source.actualHolidayOvertimeHoursStr,
				source.actualHolidayRegularCostStr,
				source.actualHolidayOvertimeCostStr,
				source.actualSpreadOfHoursCostStr,
				GETDATE()
			);

