
from sqlalchemy import Column, Date, Float, ForeignKey, Integer, PrimaryKeyConstraint, NVARCHAR, DateTime

from sqlalchemy import Column, Integer, Date, Float, NVARCHAR,Boolean
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class User(Base):
    __tablename__ = 'users'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    id = Column(Integer, nullable=False)
    type = Column(NVARCHAR(255))
    origin = Column(NVARCHAR(255))
    name = Column(NVARCHAR(255))
    legalName = Column(NVARCHAR(255))
    preferredName = Column(NVARCHAR(255))
    lastname = Column(NVARCHAR(255))
    avatar = Column(NVARCHAR(4000))
    email = Column(NVARCHAR(255))
    timezone = Column(NVARCHAR(255))
    hoursCap = Column(Float)
    active = Column(Boolean)
    deactivatedAt = Column(DateTime)
    timeclockEnabled = Column(Boolean)
    phone = Column(NVARCHAR(255))
    hireDate = Column(Date)
    birthdayDate = Column(Date)
    countryCode = Column(NVARCHAR(10))
    countryISOCode = Column(NVARCHAR(10))
    role = Column(NVARCHAR(255))
    employeeId = Column(Integer)
    address = Column(NVARCHAR(255))
    additionalEmail = Column(NVARCHAR(255))
    emergencyContact = Column(NVARCHAR(255))
    emergencyContactRelationship = Column(NVARCHAR(255))
    emergencyContactPhone = Column(NVARCHAR(255))
    emergencyContactCountryCode = Column(NVARCHAR(10))
    emergencyContactCountryISOCode = Column(NVARCHAR(10))
    status = Column(NVARCHAR(255))
    pending = Column(NVARCHAR(255))
    defaultAvatar = Column(NVARCHAR(255))
    deleted = Column(Boolean)
    createdAt = Column(DateTime)
    joinedAt = Column(DateTime)
    hidden = Column(Boolean)
    ETLCreatedAt = Column(DateTime)
    ETLUpdatedAt = Column(DateTime)


class UserTemp(Base):
    __tablename__ = '#users_temp'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    id = Column(Integer, nullable=False)
    type = Column(NVARCHAR(255))
    origin = Column(NVARCHAR(255))
    name = Column(NVARCHAR(255))
    legalName = Column(NVARCHAR(255))
    preferredName = Column(NVARCHAR(255))
    lastname = Column(NVARCHAR(255))
    avatar = Column(NVARCHAR(4000))
    email = Column(NVARCHAR(255))
    timezone = Column(NVARCHAR(255))
    hoursCap = Column(Float)
    active = Column(Boolean)
    deactivatedAt = Column(DateTime)
    timeclockEnabled = Column(Boolean)
    phone = Column(NVARCHAR(255))
    hireDate = Column(Date)
    birthdayDate = Column(Date)
    countryCode = Column(NVARCHAR(10))
    countryISOCode = Column(NVARCHAR(10))
    role = Column(NVARCHAR(255))
    employeeId = Column(Integer)
    address = Column(NVARCHAR(255))
    additionalEmail = Column(NVARCHAR(255))
    emergencyContact = Column(NVARCHAR(255))
    emergencyContactRelationship = Column(NVARCHAR(255))
    emergencyContactPhone = Column(NVARCHAR(255))
    emergencyContactCountryCode = Column(NVARCHAR(10))
    emergencyContactCountryISOCode = Column(NVARCHAR(10))
    status = Column(NVARCHAR(255))
    pending = Column(NVARCHAR(255))
    defaultAvatar = Column(NVARCHAR(255))
    deleted = Column(Boolean)
    createdAt = Column(DateTime)
    joinedAt = Column(DateTime)
    hidden = Column(Boolean)


class UserGroup(Base):
    __tablename__ = 'user_groups'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    groupId = Column(Integer)
    ETLCreatedAt = Column(DateTime)
    ETLUpdatedAt = Column(DateTime)


class UserGroupTemp(Base):
    __tablename__ = '#user_groups_temp'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    groupId = Column(Integer)


class LaborReport(Base):
    __tablename__ = 'labor_report'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=True)
    date = Column(Date, nullable=True)
    locationId = Column(Integer, nullable=True)
    positionId = Column(Integer, nullable=True)
    isSalary = Column(Boolean, nullable=True)
    estimatedWages = Column(Float, nullable=True)
    hours = Column(Float, nullable=True)
    overtimeHours = Column(Float, nullable=True)
    overtimeCost = Column(Float, nullable=True)
    overtimeDayHours = Column(Float, nullable=True)
    overtimeDayCost = Column(Float, nullable=True)
    overtimeDoubleDailyHours = Column(Float, nullable=True)
    overtimeDoubleDailyCost = Column(Float, nullable=True)
    shiftsCount = Column(Integer, nullable=True)
    scheduledHolidayHours = Column(Float, nullable=True)
    scheduledHolidayOvertimeHours = Column(Float, nullable=True)
    scheduledHolidayRegularCost = Column(Float, nullable=True)
    scheduledHolidayOvertimeCost = Column(Float, nullable=True)
    scheduledSpreadOfHoursCost = Column(Float, nullable=True)
    ptoHours = Column(Float, nullable=True)
    ptoCost = Column(Float, nullable=True)
    actualWages = Column(Float, nullable=True)
    actualHours = Column(Float, nullable=True)
    actualShiftsCount = Column(Float, nullable=True)
    actualOvertimeHours = Column(Float, nullable=True)
    actualOvertimeCost = Column(Float, nullable=True)
    actualOvertimeDayHours = Column(Float, nullable=True)
    actualOvertimeDayCost = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHours = Column(Float, nullable=True)
    actualOvertimeDoubleDailyCost = Column(Float, nullable=True)
    actualHolidayHours = Column(Float, nullable=True)
    actualHolidayOvertimeHours = Column(Float, nullable=True)
    actualHolidayRegularCost = Column(Float, nullable=True)
    actualHolidayOvertimeCost = Column(Float, nullable=True)
    actualSpreadOfHoursCost = Column(Float, nullable=True)
    estimatedWagesStr = Column(Float, nullable=True)
    hoursStr = Column(Float, nullable=True)
    overtimeHoursStr = Column(Float, nullable=True)
    overtimeCostStr = Column(Float, nullable=True)
    overtimeDayHoursStr = Column(Float, nullable=True)
    overtimeDayCostStr = Column(Float, nullable=True)
    overtimeDoubleDailyHoursStr = Column(Float, nullable=True)
    overtimeDoubleDailyCostStr = Column(Float, nullable=True)
    scheduledHolidayHoursStr = Column(Float, nullable=True)
    scheduledHolidayOvertimeHoursStr = Column(Float, nullable=True)
    scheduledHolidayRegularCostStr = Column(Float, nullable=True)
    scheduledHolidayOvertimeCostStr = Column(Float, nullable=True)
    scheduledSpreadOfHoursCostStr = Column(Float, nullable=True)
    ptoHoursStr = Column(Float, nullable=True)
    ptoCostStr = Column(Float, nullable=True)
    actualWagesStr = Column(Float, nullable=True)
    actualHoursStr = Column(Float, nullable=True)
    actualOvertimeHoursStr = Column(Float, nullable=True)
    actualOvertimeCostStr = Column(Float, nullable=True)
    actualOvertimeDayHoursStr = Column(Float, nullable=True)
    actualOvertimeDayCostStr = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHoursStr = Column(Float, nullable=True)
    actualOvertimeDoubleDailyCostStr = Column(Float, nullable=True)
    actualHolidayHoursStr = Column(Float, nullable=True)
    actualHolidayOvertimeHoursStr = Column(Float, nullable=True)
    actualHolidayRegularCostStr = Column(Float, nullable=True)
    actualHolidayOvertimeCostStr = Column(Float, nullable=True)
    actualSpreadOfHoursCostStr = Column(Float, nullable=True)
    ETLCreatedAt = Column(DateTime, nullable=True)
    ETLUpdatedAt = Column(DateTime, nullable=True)


class LaborReportTemp(Base):
    __tablename__ = '#labor_report_temp'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=True)
    date = Column(Date, nullable=True)
    locationId = Column(Integer, nullable=True)
    positionId = Column(Integer, nullable=True)
    isSalary = Column(Boolean, nullable=True)
    estimatedWages = Column(Float, nullable=True)
    hours = Column(Float, nullable=True)
    overtimeHours = Column(Float, nullable=True)
    overtimeCost = Column(Float, nullable=True)
    overtimeDayHours = Column(Float, nullable=True)
    overtimeDayCost = Column(Float, nullable=True)
    overtimeDoubleDailyHours = Column(Float, nullable=True)
    overtimeDoubleDailyCost = Column(Float, nullable=True)
    shiftsCount = Column(Integer, nullable=True)
    scheduledHolidayHours = Column(Float, nullable=True)
    scheduledHolidayOvertimeHours = Column(Float, nullable=True)
    scheduledHolidayRegularCost = Column(Float, nullable=True)
    scheduledHolidayOvertimeCost = Column(Float, nullable=True)
    scheduledSpreadOfHoursCost = Column(Float, nullable=True)
    ptoHours = Column(Float, nullable=True)
    ptoCost = Column(Float, nullable=True)
    actualWages = Column(Float, nullable=True)
    actualHours = Column(Float, nullable=True)
    actualShiftsCount = Column(Float, nullable=True)
    actualOvertimeHours = Column(Float, nullable=True)
    actualOvertimeCost = Column(Float, nullable=True)
    actualOvertimeDayHours = Column(Float, nullable=True)
    actualOvertimeDayCost = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHours = Column(Float, nullable=True)
    actualOvertimeDoubleDailyCost = Column(Float, nullable=True)
    actualHolidayHours = Column(Float, nullable=True)
    actualHolidayOvertimeHours = Column(Float, nullable=True)
    actualHolidayRegularCost = Column(Float, nullable=True)
    actualHolidayOvertimeCost = Column(Float, nullable=True)
    actualSpreadOfHoursCost = Column(Float, nullable=True)
    estimatedWagesStr = Column(Float, nullable=True)
    hoursStr = Column(Float, nullable=True)
    overtimeHoursStr = Column(Float, nullable=True)
    overtimeCostStr = Column(Float, nullable=True)
    overtimeDayHoursStr = Column(Float, nullable=True)
    overtimeDayCostStr = Column(Float, nullable=True)
    overtimeDoubleDailyHoursStr = Column(Float, nullable=True)
    overtimeDoubleDailyCostStr = Column(Float, nullable=True)
    scheduledHolidayHoursStr = Column(Float, nullable=True)
    scheduledHolidayOvertimeHoursStr = Column(Float, nullable=True)
    scheduledHolidayRegularCostStr = Column(Float, nullable=True)
    scheduledHolidayOvertimeCostStr = Column(Float, nullable=True)
    scheduledSpreadOfHoursCostStr = Column(Float, nullable=True)
    ptoHoursStr = Column(Float, nullable=True)
    ptoCostStr = Column(Float, nullable=True)
    actualWagesStr = Column(Float, nullable=True)
    actualHoursStr = Column(Float, nullable=True)
    actualOvertimeHoursStr = Column(Float, nullable=True)
    actualOvertimeCostStr = Column(Float, nullable=True)
    actualOvertimeDayHoursStr = Column(Float, nullable=True)
    actualOvertimeDayCostStr = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHoursStr = Column(Float, nullable=True)
    actualOvertimeDoubleDailyCostStr = Column(Float, nullable=True)
    actualHolidayHoursStr = Column(Float, nullable=True)
    actualHolidayOvertimeHoursStr = Column(Float, nullable=True)
    actualHolidayRegularCostStr = Column(Float, nullable=True)
    actualHolidayOvertimeCostStr = Column(Float, nullable=True)
    actualSpreadOfHoursCostStr = Column(Float, nullable=True)


class LeaveReport(Base):
    __tablename__ = 'leave_report'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    date = Column(Date,nullable=True)
    leaveTypeId = Column(Integer, nullable=False)
    approved = Column(Integer, nullable=True)
    approvedMinutes = Column(Integer, nullable=True)
    unpaid = Column(Integer, nullable=True)
    unpaidMinutes = Column(Integer, nullable=True)
    deniedMinutes = Column(Float, nullable=True)
    deniedDays = Column(Float, nullable=True)
    ptoCost = Column(Float, nullable=True)
    pending = Column(Integer, nullable=True)
    pendingMinutes = Column(Integer, nullable=True)
    remaining = Column(Float, nullable=True)
    ETLCreatedAt = Column(DateTime, nullable=True)
    ETLUpdatedAt = Column(DateTime, nullable=True)


class LeaveReportTemp(Base):
    __tablename__ = '#leave_report_temp'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    date = Column(Date,nullable=True)
    leaveTypeId = Column(Integer, nullable=False)
    approved = Column(Integer, nullable=True)
    approvedMinutes = Column(Integer, nullable=True)
    unpaid = Column(Integer, nullable=True)
    unpaidMinutes = Column(Integer, nullable=True)
    deniedMinutes = Column(Float, nullable=True)
    deniedDays = Column(Float, nullable=True)
    ptoCost = Column(Float, nullable=True)
    pending = Column(Integer, nullable=True)
    pendingMinutes = Column(Integer, nullable=True)
    remaining = Column(Float, nullable=True)


class PayrollReport(Base):
    __tablename__ = 'payroll_report'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    date = Column(Date,nullable=True)
    locationId = Column(Integer, nullable=True)
    positionId = Column(Integer, nullable=True)
    actualHours = Column(Float, nullable=True)
    actualHoursStr = Column(Float, nullable=True)
    status = Column(NVARCHAR(255), nullable=True)
    actualHolidayHours = Column(Float, nullable=True)
    actualHolidayHoursStr = Column(Float, nullable=True)
    actualHolidayCost = Column(Float, nullable=True)
    actualHolidayCostStr = Column(Float, nullable=True)
    actualSpreadOfHoursCost = Column(Float, nullable=True)
    actualSpreadOfHoursCostStr = Column(Float, nullable=True)
    isSalary = Column(Boolean, nullable=True)
    isOnSalary = Column(Boolean, nullable=True)
    ptoHours = Column(Float, nullable=True)
    ptoHoursStr = Column(Float, nullable=True)
    ptoCost = Column(Float, nullable=True)
    ptoCostStr = Column(Float, nullable=True)
    premiumPayCost = Column(Float, nullable=True)
    actualOvertimeHours = Column(Float, nullable=True)
    actualOvertimeHoursStr = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHours = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHoursStr = Column(Float, nullable=True)
    actualOvertimeCost = Column(Float, nullable=True)
    actualOvertimeCostStr = Column(Float, nullable=True)
    actualHolidayOvertimeHours = Column(Float, nullable=True)
    actualHolidayOvertimeHoursStr = Column(Float, nullable=True)
    actualHolidayOvertimeCost = Column(Float, nullable=True)
    actualHolidayOvertimeCostStr = Column(Float, nullable=True)
    shiftId = Column(NVARCHAR(255), nullable=True)
    shiftDuration = Column(Float, nullable=True)
    shiftActualDuration = Column(Float, nullable=True)
    shiftBreakDuration = Column(Float, nullable=True)
    shiftActualBreakDuration = Column(Float, nullable=True)
    wage = Column(Float, nullable=True)
    wageStr = Column(Float, nullable=True)
    actualWages = Column(Float, nullable=True)
    actualWagesStr = Column(Float, nullable=True)
    ETLCreatedAt = Column(DateTime, nullable=True)
    ETLUpdatedAt = Column(DateTime, nullable=True)


class PayrollReportTemp(Base):
    __tablename__ = '#payroll_report_temp'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    date = Column(Date,nullable=True)
    locationId = Column(Integer, nullable=True)
    positionId = Column(Integer, nullable=True)
    actualHours = Column(Float, nullable=True)
    actualHoursStr = Column(Float, nullable=True)
    status = Column(NVARCHAR(255), nullable=True)
    actualHolidayHours = Column(Float, nullable=True)
    actualHolidayHoursStr = Column(Float, nullable=True)
    actualHolidayCost = Column(Float, nullable=True)
    actualHolidayCostStr = Column(Float, nullable=True)
    actualSpreadOfHoursCost = Column(Float, nullable=True)
    actualSpreadOfHoursCostStr = Column(Float, nullable=True)
    isSalary = Column(Boolean, nullable=True)
    isOnSalary = Column(Boolean, nullable=True)
    ptoHours = Column(Float, nullable=True)
    ptoHoursStr = Column(Float, nullable=True)
    ptoCost = Column(Float, nullable=True)
    ptoCostStr = Column(Float, nullable=True)
    premiumPayCost = Column(Float, nullable=True)
    actualOvertimeHours = Column(Float, nullable=True)
    actualOvertimeHoursStr = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHours = Column(Float, nullable=True)
    actualOvertimeDoubleDailyHoursStr = Column(Float, nullable=True)
    actualOvertimeCost = Column(Float, nullable=True)
    actualOvertimeCostStr = Column(Float, nullable=True)
    actualHolidayOvertimeHours = Column(Float, nullable=True)
    actualHolidayOvertimeHoursStr = Column(Float, nullable=True)
    actualHolidayOvertimeCost = Column(Float, nullable=True)
    actualHolidayOvertimeCostStr = Column(Float, nullable=True)
    shiftId = Column(NVARCHAR(255), nullable=True)
    shiftDuration = Column(Float, nullable=True)
    shiftActualDuration = Column(Float, nullable=True)
    shiftBreakDuration = Column(Float, nullable=True)
    shiftActualBreakDuration = Column(Float, nullable=True)
    wage = Column(Float, nullable=True)
    wageStr = Column(Float, nullable=True)
    actualWages = Column(Float, nullable=True)
    actualWagesStr = Column(Float, nullable=True)


class NoShows(Base):
    __tablename__ = 'noshows'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    date = Column(Date,nullable=True)
    locationId = Column(Integer, nullable=False)
    positionId = Column(Integer, nullable=False)
    scheduled = Column(Integer, nullable=True)
    scheduledMinutes = Column(Integer, nullable=True)
    lateCount = Column(Integer, nullable=True)
    actual = Column(Integer, nullable=True)
    actualMinutes = Column(Integer, nullable=True)
    sickCallout = Column(Integer, nullable=True)
    noShow = Column(Integer, nullable=True)
    ETLCreatedAt = Column(DateTime, nullable=True)
    ETLUpdatedAt = Column(DateTime, nullable=True)


class NoShowsTemp(Base):
    __tablename__ = '#noshows_temp'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    userId = Column(Integer, nullable=False)
    date = Column(Date,nullable=True)
    locationId = Column(Integer, nullable=False)
    positionId = Column(Integer, nullable=False)
    scheduled = Column(Integer, nullable=True)
    scheduledMinutes = Column(Integer, nullable=True)
    lateCount = Column(Integer, nullable=True)
    actual = Column(Integer, nullable=True)
    actualMinutes = Column(Integer, nullable=True)
    sickCallout = Column(Integer, nullable=True)
    noShow = Column(Integer, nullable=True)


class Group(Base):
    __tablename__ = 'groups'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    id = Column(Integer, nullable=False)
    type = Column(NVARCHAR(255), nullable=True)
    origin = Column(NVARCHAR(255), nullable=True)
    name = Column(NVARCHAR(255), nullable=True)
    externalId = Column(NVARCHAR(255), nullable=True)
    archivedAt = Column(DateTime, nullable=True)
    memberCount = Column(Integer, nullable=True)
    ETLCreatedAt = Column(DateTime, nullable=True)
    ETLUpdatedAt = Column(DateTime, nullable=True)


class GroupTemp(Base):
    __tablename__ = '#groups_temp'
    
    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    id = Column(Integer, nullable=False)
    type = Column(NVARCHAR(255), nullable=True)
    origin = Column(NVARCHAR(255), nullable=True)
    name = Column(NVARCHAR(255), nullable=True)
    externalId = Column(NVARCHAR(255), nullable=True)
    archivedAt = Column(DateTime, nullable=True)
    memberCount = Column(Integer, nullable=True)
    

class LeaveType(Base):
    __tablename__ = 'leave_types'

    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    id = Column(Integer, nullable=False)
    type = Column(NVARCHAR(255), nullable=False)
    name = Column(NVARCHAR(255), nullable=False)
    paid = Column(Boolean, nullable=True)
    enabled = Column(Boolean, nullable=True)
    cap = Column(NVARCHAR(255), nullable=True)
    available = Column(Boolean, nullable=True)
    ETLCreatedAt = Column(DateTime, nullable=True)
    ETLUpdatedAt = Column(DateTime, nullable=True)



class LeaveTypeTemp(Base):
    __tablename__ = '#leave_types_temp'

    systemGeneratedId = Column(Integer, primary_key=True, autoincrement=True)
    id = Column(Integer, nullable=False)
    type = Column(NVARCHAR(255), nullable=False)
    name = Column(NVARCHAR(255), nullable=False)
    paid = Column(Boolean, nullable=True)
    enabled = Column(Boolean, nullable=True)
    cap = Column(NVARCHAR(255), nullable=True)
    available = Column(Boolean, nullable=True)



class Logsheet(Base):
    __tablename__ = 'logsheet'

    id = Column(Integer, primary_key=True, autoincrement=True)
    tableName = Column(NVARCHAR(255), nullable=False)
    startTime = Column(NVARCHAR(255), nullable=False)
    endTime = Column(NVARCHAR(255), nullable=False)
    error = Column(NVARCHAR(4000),nullable=True)
    noRecordsCreated = Column(Integer, nullable=True)
    noRecordsUpdated = Column(Integer, nullable=True)
    createdAt = Column(DateTime, nullable=True)